table 'Italy Grid'
	lineageTag: d34f8aa7-dfae-4495-b74f-43e3cc351d2d

	column Region
		dataType: string
		lineageTag: e63204bf-9486-419c-9748-bb938f140969
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'X Pos'
		dataType: int64
		formatString: 0
		lineageTag: 669c5c3a-ff1a-4b2f-9b25-2d8a09e87a2d
		summarizeBy: sum
		sourceColumn: X Pos

		annotation SummarizationSetBy = Automatic

	column 'Y Pos'
		dataType: int64
		formatString: 0
		lineageTag: 04ccb41b-cd2d-4f25-a0cd-ccd837966ce4
		summarizeBy: sum
		sourceColumn: Y Pos

		annotation SummarizationSetBy = Automatic

	partition 'Italy Grid' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("RY1LDsMgDETv4nU2Lf0uTUQjJCgRJF0Ucf9rNBmbZoE0T/MG10qcCg10wmtDpSW7LZs/z95pfwaHFJE7f9xbfeFX9lu+HL6f1DdgF736wgvuG2x2jpx1L7xGq3wFs83InQN/tb/JPgXthQv+2+/fwSNH7YUtF7id53VCPvyg/UP+86Pun9TaDw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Region = _t, #"X Pos" = _t, #"Y Pos" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Region", type text}, {"X Pos", Int64.Type}, {"Y Pos", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

