table 'World Map'
	lineageTag: 3be2578d-5f13-4376-997c-2e32cd458168

	measure X = ```
			
			
			    SUM('World Map'[X Pos])
			```
		lineageTag: 6edb6edf-af56-47ea-ab07-d753fa87ae87

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Y = ```
			
			
			    SUM('World Map'[Y Pos])
			```
		lineageTag: e1229ad1-920d-425b-8855-89da4207c690

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Reg Max' = ```
			
			
			  10
			    
			```
		lineageTag: 3d3a88e8-995c-413d-a873-3374076b9205

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column name
		dataType: string
		lineageTag: 26484fe1-b434-4a68-80cc-8972a5518f5c
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column Code1
		dataType: string
		lineageTag: 8c71d2ed-6b01-408a-9b74-143f54f3ed50
		summarizeBy: none
		sourceColumn: Code1

		annotation SummarizationSetBy = Automatic

	column 'alpha.3'
		dataType: string
		lineageTag: 1ed34cc2-d74c-4b23-b633-a4dfc7df23f9
		summarizeBy: none
		sourceColumn: alpha.3

		annotation SummarizationSetBy = Automatic

	column 'country.code'
		dataType: int64
		formatString: 0
		lineageTag: 085d19a7-1928-4542-a05c-25ef789e687a
		summarizeBy: sum
		sourceColumn: country.code

		annotation SummarizationSetBy = Automatic

	column 'iso_3166.2'
		dataType: string
		lineageTag: 3ff5e9c5-11a9-4a49-a248-1768a074fd83
		summarizeBy: none
		sourceColumn: iso_3166.2

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: d73471db-d25c-49e6-a70a-b10597c31f54
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column 'sub.region'
		dataType: string
		lineageTag: 1b909668-43e8-423c-aa8d-bcbf60974991
		summarizeBy: none
		sourceColumn: sub.region

		annotation SummarizationSetBy = Automatic

	column 'region.code'
		dataType: string
		lineageTag: dfcb7375-a35f-4d69-a858-869aeec006d1
		summarizeBy: none
		sourceColumn: region.code

		annotation SummarizationSetBy = Automatic

	column 'sub.region.code'
		dataType: string
		lineageTag: f70c742e-432d-4f5b-9704-bd36dca1283a
		summarizeBy: none
		sourceColumn: sub.region.code

		annotation SummarizationSetBy = Automatic

	column 'X Pos'
		dataType: int64
		formatString: 0
		lineageTag: acd0686b-2059-4470-95ca-ab2f7bb91bab
		summarizeBy: sum
		sourceColumn: X Pos

		annotation SummarizationSetBy = Automatic

	column 'Y Pos'
		dataType: int64
		formatString: 0
		lineageTag: 959e7fc1-7de8-4597-b071-4acc0a8cdbbb
		summarizeBy: sum
		sourceColumn: Y Pos

		annotation SummarizationSetBy = Automatic

	partition 'World Map' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lVzZduJIEv0VHZ56zpmaww6eNzYLjAQUErhMTz8koMbqAsktkN32d80fzI+N4mZq", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [name = _t, alpha.2 = _t, alpha.3 = _t, country.code = _t, iso_3166.2 = _t, region = _t, sub.region = _t, region.code = _t, sub.region.code = _t, #"X Pos" = _t, #"Y Pos" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"name", type text}, {"alpha.2", type text}, {"alpha.3", type text}, {"country.code", Int64.Type}, {"iso_3166.2", type text}, {"region", type text}, {"sub.region", type text}, {"region.code", type text}, {"sub.region.code", type text}, {"X Pos", Int64.Type}, {"Y Pos", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"alpha.2", "Code1"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table

